spring.application.name=mira-gateway
#DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# jwt
security.jwt.secret=${SECRET}
security.jwt.issuer=${ISSUER}
security.jwt.access-token-minutes=${ACCESS_TOKEN_MINUTES}

# ENV
mira.checkout.base-url=${CHECKOUT_BASE_URL:http://localhost:5173/checkout}
