spring.application.name=mira-gateway
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secret=kH+g0NLJuxvsd4U6RIR+j1y0WzhvIJbCuSZwF2RqxG0=
security.jwt.issuer=emre
security.jwt.access-token-minutes=30